# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - extra_blocks
  label: "ListingsAll"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    sectionId:
    showNote: true
    filterCollection:
    heading: bookshop:structure:headingBlocks
    tags:
    showExpired: false
    showAvailable: true
    showDisqualified: false
    showGeneral: true
    noListingsHeading: bookshop:structure:headingBlocks
  styles:
    color_group: primary
    card_color_group: primary
    colorFromGroup: background
    listingCardStyle: default

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  tags:
    comment: >-
      Filter by specifc tags (set up in the listing tags file) to show only those listings. Leave blank to show all.
    type: multiselect
    options:
      values: data.listingTags
  filterCollection:
    hidden: true
    type: select
    options:
      allow_empty: true
      values: data.listings.filtering[*]
      value_key: id
      text_key: filterCollectionName
  listingCardStyle:
    type: select
    options:
      allow_empty: false
      value_key: id
      values:
        - name: Default
          id: default
        - name: Horizontal
          id: horizontal